import type { RestaurantMenu } from "../types/Restaurant";
export const RestaurantMenuItems:RestaurantMenu[] = [
  // Paradise Biryani - restaurantId: 1
  {
    id: 101,
    restaurantId: 1,
    name: "Chicken Biryani",
    description: "Aromatic basmati rice cooked with tender chicken and spices.",
    price: 280,
    category: "Biryani",
    isVeg: false,
  },
  {
    id: 102,
    restaurantId: 1,
    name: "Mutton Biryani",
    description: "Flavorful biryani prepared with tender mutton and aromatic spices.",
    price: 350,
    category: "Biryani",
    isVeg: false,
  },
  {
    id: 103,
    restaurantId: 1,
    name: "Veg Biryani",
    description: "Fragrant basmati rice cooked with fresh vegetables and spices.",
    price: 220,
    category: "Biryani",
    isVeg: true,
  },
  {
    id: 104,
    restaurantId: 1,
    name: "Chicken 65",
    description: "Crispy fried chicken pieces tossed with Indian spices.",
    price: 190,
    category: "Starters",
    isVeg: false,
  },

  // Meghana Foods - restaurantId: 2
  {
    id: 201,
    restaurantId: 2,
    name: "Meghana Special Chicken Biryani",
    description: "Spicy and flavorful chicken biryani with aromatic basmati rice.",
    price: 300,
    category: "Biryani",
    isVeg: false,
  },
  {
    id: 202,
    restaurantId: 2,
    name: "Paneer Biryani",
    description: "Aromatic rice cooked with soft paneer and flavorful spices.",
    price: 240,
    category: "Biryani",
    isVeg: true,
  },
  {
    id: 203,
    restaurantId: 2,
    name: "Paneer Tikka",
    description: "Grilled paneer cubes marinated with Indian spices.",
    price: 180,
    category: "Starters",
    isVeg: true,
  },

  // Pizza Hut - restaurantId: 3
  {
    id: 301,
    restaurantId: 3,
    name: "Margherita Pizza",
    description: "Classic pizza topped with tomato sauce, mozzarella and herbs.",
    price: 249,
    category: "Pizza",
    isVeg: true,
  },
  {
    id: 302,
    restaurantId: 3,
    name: "Chicken Supreme Pizza",
    description: "Loaded pizza with chicken, vegetables and extra cheese.",
    price: 399,
    category: "Pizza",
    isVeg: false,
  },
  {
    id: 303,
    restaurantId: 3,
    name: "Garlic Bread",
    description: "Soft baked bread topped with garlic butter and herbs.",
    price: 149,
    category: "Sides",
    isVeg: true,
  },

  // Burger King - restaurantId: 4
  {
    id: 401,
    restaurantId: 4,
    name: "Whopper",
    description: "Classic burger with a juicy patty, vegetables and signature sauce.",
    price: 249,
    category: "Burgers",
    isVeg: false,
  },
  {
    id: 402,
    restaurantId: 4,
    name: "Veg Whopper",
    description: "Crispy vegetarian patty with fresh vegetables and sauces.",
    price: 199,
    category: "Burgers",
    isVeg: true,
  },
  {
    id: 403,
    restaurantId: 4,
    name: "French Fries",
    description: "Crispy golden potato fries.",
    price: 119,
    category: "Sides",
    isVeg: true,
  },

  // Beijing Bites - restaurantId: 5
  {
    id: 501,
    restaurantId: 5,
    name: "Chicken Fried Rice",
    description: "Chinese-style fried rice tossed with chicken and vegetables.",
    price: 220,
    category: "Rice",
    isVeg: false,
  },
  {
    id: 502,
    restaurantId: 5,
    name: "Veg Noodles",
    description: "Stir-fried noodles with fresh vegetables and sauces.",
    price: 180,
    category: "Noodles",
    isVeg: true,
  },
  {
    id: 503,
    restaurantId: 5,
    name: "Chicken Manchurian",
    description: "Crispy chicken tossed in a spicy Manchurian sauce.",
    price: 240,
    category: "Starters",
    isVeg: false,
  },

  // Saravana Bhavan - restaurantId: 6
  {
    id: 601,
    restaurantId: 6,
    name: "Masala Dosa",
    description: "Crispy dosa served with potato masala, chutney and sambar.",
    price: 120,
    category: "South Indian",
    isVeg: true,
  },
  {
    id: 602,
    restaurantId: 6,
    name: "Idli Vada",
    description: "Soft idlis and crispy vada served with sambar and chutney.",
    price: 100,
    category: "South Indian",
    isVeg: true,
  },
  {
    id: 603,
    restaurantId: 6,
    name: "Paneer Dosa",
    description: "Crispy dosa filled with flavorful paneer masala.",
    price: 160,
    category: "South Indian",
    isVeg: true,
  },

  // Cream Stone - restaurantId: 7
  {
    id: 701,
    restaurantId: 7,
    name: "Chocolate Ice Cream",
    description: "Rich and creamy chocolate ice cream.",
    price: 180,
    category: "Ice Cream",
    isVeg: true,
  },
  {
    id: 702,
    restaurantId: 7,
    name: "Brownie Sundae",
    description: "Chocolate brownie served with creamy ice cream and toppings.",
    price: 250,
    category: "Desserts",
    isVeg: true,
  },

  // Absolute Barbecues - restaurantId: 8
  {
    id: 801,
    restaurantId: 8,
    name: "Chicken Tikka",
    description: "Juicy grilled chicken pieces marinated with aromatic spices.",
    price: 280,
    category: "Starters",
    isVeg: false,
  },
  {
    id: 802,
    restaurantId: 8,
    name: "Paneer Tikka",
    description: "Grilled paneer cubes marinated in spicy yogurt.",
    price: 240,
    category: "Starters",
    isVeg: true,
  },
  {
    id: 803,
    restaurantId: 8,
    name: "Grilled Chicken",
    description: "Tender chicken grilled with herbs and spices.",
    price: 350,
    category: "Main Course",
    isVeg: false,
  },
];